//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDbViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsMonthPlan
    {
        public int detailID { get; set; }
        public System.DateTime date { get; set; }
        public int departmentID { get; set; }
        public int mustProduce { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Detail Detail { get; set; }
    }
}
