//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDbViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerInformationView
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public string tableNumber { get; set; }
        public string department { get; set; }
        public string speciality { get; set; }
        public int category { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
    }
}
