//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAccountView
    {
        public int WorkerInformationId { get; set; }
        public int detailID { get; set; }
        public System.DateTime date { get; set; }
        public int madeCount { get; set; }
        public int norm { get; set; }
        public int defectCount { get; set; }
    
        public virtual WorkerInformationView WorkerInformation { get; set; }
    }
}
