//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace FactoryDataModel
{
    public partial class DailyAccountView
    {
        public int workerID { get; set; }
        public int detailID { get; set; }
        public DateTime date { get; set; }
        public int madeCount { get; set; }
        public int norm { get; set; }
        public int defectCount { get; set; }
    
        public virtual WorkerInformationView WorkerInformation { get; set; }
        public virtual DetailsView Detail { get; set; }
    }
}
