//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthAccountView
    {
        public string department { get; set; }
        public string detail { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public int plan { get; set; }
        public Nullable<int> made { get; set; }
        public Nullable<int> percentDefectOfMade { get; set; }
    }
}
