//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.DailyAccounts = new HashSet<DailyAccount>();
        }
    
        public int id { get; set; }
        public string tableNumber { get; set; }
        public int departmentID { get; set; }
        public int specialityID { get; set; }
        public int category { get; set; }
        public System.DateTime workStartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyAccount> DailyAccounts { get; set; }
        public virtual Department Department { get; set; }
        public virtual WorkerSpeciality WorkerSpeciality { get; set; }
        public virtual WorkersInformation WorkersInformation { get; set; }
    }
}
